services:
  dev-container:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ..:/workspace:cached
      - backend_node_modules:/workspace/backend/node_modules
      - frontend_node_modules:/workspace/frontend/node_modules
    env_file:
      - ../.env
    depends_on:
      - db
    command: sleep infinity
    # network_mode: host

  db:
    image: postgres:18-alpine
    # volumes:
    #   - postgres-data:/var/lib/postgresql/data
    environment:
      # To change
      - POSTGRES_DB=medicine-store
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=adminpassword
    ports:
      - "5432:5432"

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    # volumes:
    #   - redis_data:/data

volumes:
  # postgres-data:
  redis_data:
  backend_node_modules:
  frontend_node_modules:
